
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Geeksasaeng' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Geeksasaeng
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'naveridlogin-sdk-ios'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Messaging'
  pod 'lottie-ios'
  pod 'Then'
  pod 'RMQClient'
  pod 'RealmSwift'
  pod 'Starscream'
  pod 'NMapsMap', '3.10.0'

  target 'GeeksasaengTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeeksasaengUITests' do
    # Pods for testing
  end

end