# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Geeksasaeng' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Geeksasaeng
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'naveridlogin-sdk-ios'

  target 'GeeksasaengTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeeksasaengUITests' do
    # Pods for testing
  end

end
